{
 "title": "UR MVP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Где высокий потенциальный спрос",
   "type": "table",
   "description": "Где модель видит высокий потенциальный спрос, хотя фактических поездок пока не было",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "SELECT *\r\nFROM mart.ur_link_scores_latest\r\nWHERE trip_cnt = 0 AND p_demand > 0.7\r\nORDER BY p_demand DESC\r\nLIMIT 200;\r\n"
    }
   ]
  },
  {
   "title": "Топ районов по входящему спросу (по NAME конца)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "WITH last AS (\r\n  SELECT max(run_ts) AS run_ts\r\n  FROM mart.ur_link_scores\r\n)\r\nSELECT\r\n  dc.name AS name_end,\r\n  round(avg(s.p_demand)::numeric, 3) AS avg_p_in,\r\n  round(sum(s.p_demand)::numeric, 3) AS total_p_in,\r\n  count(*) FILTER (WHERE s.p_demand > 0.7) AS strong_links\r\nFROM mart.ur_link_scores s\r\nJOIN last t ON s.run_ts = t.run_ts\r\nJOIN raw.dist_cent dc\r\n  ON dc.no = s.no_end\r\nGROUP BY dc.name\r\nORDER BY total_p_in DESC\r\nLIMIT 30;\r\n"
    }
   ]
  },
  {
   "title": "Топ районов по исходящему спросу (по NAME)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "WITH last AS (\r\n  SELECT max(run_ts) AS run_ts\r\n  FROM mart.ur_link_scores\r\n)\r\nSELECT\r\n  l.name AS name_start,\r\n  round(avg(s.p_demand)::numeric, 3) AS avg_p_out,\r\n  round(sum(s.p_demand)::numeric, 3) AS total_p_out,\r\n  count(*) FILTER (WHERE s.p_demand > 0.7) AS strong_links\r\nFROM mart.ur_link_scores s\r\nJOIN last t ON s.run_ts = t.run_ts\r\nJOIN mart.no_links l\r\n  ON l.no_start = s.no_start AND l.no_end = s.no_end\r\nGROUP BY l.name\r\nORDER BY total_p_out DESC\r\nLIMIT 30;\r\n"
    }
   ]
  },
  {
   "title": "Входящий спрос",
   "type": "table",
   "description": "Куда чаще всего хотят ехать",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "SELECT\r\n  no_end,\r\n  avg(p_demand) AS avg_in_demand,\r\n  sum(p_demand) AS total_in_demand\r\nFROM mart.ur_link_scores\r\nWHERE run_ts = (SELECT max(run_ts) FROM mart.ur_link_scores)\r\nGROUP BY no_end\r\nORDER BY total_in_demand DESC;\r\n"
    }
   ]
  },
  {
   "title": "Высокий латентный спрос",
   "type": "table",
   "description": "Поездок ещё нет, но вероятность высокая",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "WITH last AS (\r\n  SELECT max(run_ts) AS run_ts\r\n  FROM mart.ur_link_scores\r\n)\r\nSELECT\r\n  s.no_start,\r\n  l.name AS name_start,\r\n  s.no_end,\r\n  round(s.p_demand::numeric, 3) AS p_demand,\r\n  round(s.distance_km::numeric, 2) AS distance_km,\r\n  COALESCE(l.trip_cnt, 0) AS trip_cnt\r\nFROM mart.ur_link_scores s\r\nJOIN last t ON s.run_ts = t.run_ts\r\nJOIN mart.no_links l\r\n  ON l.no_start = s.no_start AND l.no_end = s.no_end\r\nWHERE COALESCE(l.trip_cnt, 0) = 0\r\n  AND s.p_demand > 0.7\r\nORDER BY s.p_demand DESC\r\nLIMIT 200;\r\n"
    }
   ]
  },
  {
   "title": "Наиболее прогнозируемые связи спроса (p_demand)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "WITH last AS (\r\n  SELECT max(run_ts) AS run_ts\r\n  FROM mart.ur_link_scores\r\n)\r\nSELECT\r\n  s.no_start,\r\n  s.no_end,\r\n  round(s.p_demand::numeric, 3) AS p_demand,\r\n  round(s.distance_km::numeric, 2) AS distance_km\r\nFROM mart.ur_link_scores s\r\nJOIN last l ON s.run_ts = l.run_ts\r\nORDER BY s.p_demand DESC\r\nLIMIT 200;\r\n"
    }
   ]
  },
  {
   "title": "Исходящий спрос по району",
   "type": "table",
   "description": "Где район «генерирует» поездки",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "urmvp",
     "rawSql": "SELECT\r\n  no_start,\r\n  avg(p_demand) AS avg_out_demand,\r\n  sum(p_demand) AS total_out_demand\r\nFROM mart.ur_link_scores\r\nWHERE run_ts = (SELECT max(run_ts) FROM mart.ur_link_scores)\r\nGROUP BY no_start\r\nORDER BY total_out_demand DESC;\r\n"
    }
   ]
  }
 ]
}